### ISSUE TITLE
Issue running demo

### ISSUE THREAD

**Issue by xinyangbing** [staciawyman/blender#4]
I am running into the following issue running the DEMO file in blender: 
sh run_blender.sh ./BOWTIE2_INDEXES/hg38.fa DEMO/bwa/BW43_VEFGA.chr19.bam DEMO/bwa/BW44_BFP_control.chr19.bam GACCCCCTCCACCCCGCCTC DEMO/blender
[W::hts_idx_load2] The index file is older than the data file: DEMO/bwa/BW43_VEFGA.chr19.bam.bai
(followed by a bunch of these)
run_blender.sh: 37: run_blender.sh: GUIDE+=NGG: not found
Traceback (most recent call last):
  File "draw_blender_fig.py", line 127, in <module>
    main()
  File "draw_blender_fig.py", line 121, in main
    visualizeOfftargets(sys.argv[1], sys.argv[2], sys.argv[3], title=title)
  File "draw_blender_fig.py", line 90, in visualizeOfftargets
    if c == target_guide[i] or target_guide[i] == 'N':
IndexError: string index out of range

**Comment by staciawyman** [comment]
Hi, It says the index file is older than the bam file, so try changing the timestamp of the index file with 

`$ touch DEMO/bwa/BW43_VEFGA.chr19.bam.bai`

**Comment by staciawyman** [comment]
I think it must be that your version of bash does not support “+=“. I’ll change the code but I’m not at my computer to change it right now. If you change this line:

GUIDE+=“NGG”

To this:

GUIDE=“${GUIDE}NGG”

It should work.

**Comment by xinyangbing** [comment]
Thank you so much this worked!
